@echo off
setlocal EnableExtensions
chcp 65001 >nul
set "ROOT=%~1"
if "%ROOT%"=="" set "ROOT=%CD%"
if not exist "%ROOT%" mkdir "%ROOT%"
pushd "%ROOT%"
echo Creating directories...
if not exist ".github\workflows" mkdir ".github\workflows"
if not exist "configs\model_configs" mkdir "configs\model_configs"
if not exist "src\fire_smoke_dt\shared" mkdir "src\fire_smoke_dt\shared"
if not exist "src\fire_smoke_dt\bim_graph" mkdir "src\fire_smoke_dt\bim_graph"
if not exist "src\fire_smoke_dt\scenario" mkdir "src\fire_smoke_dt\scenario"
if not exist "src\fire_smoke_dt\cfast_sim" mkdir "src\fire_smoke_dt\cfast_sim"
if not exist "src\fire_smoke_dt\fds_sim" mkdir "src\fire_smoke_dt\fds_sim"
if not exist "src\fire_smoke_dt\comparison" mkdir "src\fire_smoke_dt\comparison"
if not exist "src\fire_smoke_dt\iot_sim" mkdir "src\fire_smoke_dt\iot_sim"
if not exist "src\fire_smoke_dt\dataset" mkdir "src\fire_smoke_dt\dataset"
if not exist "src\fire_smoke_dt\models\baselines" mkdir "src\fire_smoke_dt\models\baselines"
if not exist "src\fire_smoke_dt\training" mkdir "src\fire_smoke_dt\training"
if not exist "dashboard\backend\app\routers" mkdir "dashboard\backend\app\routers"
if not exist "dashboard\frontend\src" mkdir "dashboard\frontend\src"
if not exist "tests\unit\shared" mkdir "tests\unit\shared"
if not exist "tests\unit\bim_graph" mkdir "tests\unit\bim_graph"
if not exist "tests\unit\iot_sim" mkdir "tests\unit\iot_sim"
if not exist "tests\unit\dataset" mkdir "tests\unit\dataset"
if not exist "tests\integration" mkdir "tests\integration"
if not exist "tests\fixtures" mkdir "tests\fixtures"
if not exist "data\raw_ifc" mkdir "data\raw_ifc"
if not exist "data\cfast_raw" mkdir "data\cfast_raw"
if not exist "data\fds_raw" mkdir "data\fds_raw"
if not exist "data\processed" mkdir "data\processed"
if not exist "data\datasets" mkdir "data\datasets"
if not exist "outputs" mkdir "outputs"
if not exist "notebooks" mkdir "notebooks"
if not exist "docs\modules" mkdir "docs\modules"
if not exist "docs\checkin_notes" mkdir "docs\checkin_notes"
if not exist "docs\learning_notes" mkdir "docs\learning_notes"
if not exist "report" mkdir "report"
if not exist "scripts" mkdir "scripts"
echo Creating empty placeholders only...
if not exist ".env.example" type nul > ".env.example"
if not exist ".github\CODEOWNERS" type nul > ".github\CODEOWNERS"
if not exist ".github\PULL_REQUEST_TEMPLATE.md" type nul > ".github\PULL_REQUEST_TEMPLATE.md"
if not exist ".github\workflows\ci.yml" type nul > ".github\workflows\ci.yml"
if not exist ".gitignore" type nul > ".gitignore"
if not exist "ARCHITECTURE.md" type nul > "ARCHITECTURE.md"
if not exist "CONTRIBUTING.md" type nul > "CONTRIBUTING.md"
if not exist "MODULE_OWNERS.md" type nul > "MODULE_OWNERS.md"
if not exist "README.md" type nul > "README.md"
if not exist "SCOPE.md" type nul > "SCOPE.md"
if not exist "configs\README.md" type nul > "configs\README.md"
if not exist "configs\label_rules.yaml" type nul > "configs\label_rules.yaml"
if not exist "configs\model_configs\bat_gnn.yaml" type nul > "configs\model_configs\bat_gnn.yaml"
if not exist "configs\noise_presets.yaml" type nul > "configs\noise_presets.yaml"
if not exist "configs\scenario_schema.yaml" type nul > "configs\scenario_schema.yaml"
if not exist "configs\schema_version.yaml" type nul > "configs\schema_version.yaml"
if not exist "configs\sensor_schema.yaml" type nul > "configs\sensor_schema.yaml"
if not exist "configs\split_rules.yaml" type nul > "configs\split_rules.yaml"
if not exist "dashboard\__init__.py" type nul > "dashboard\__init__.py"
if not exist "dashboard\backend\Dockerfile" type nul > "dashboard\backend\Dockerfile"
if not exist "dashboard\backend\README.md" type nul > "dashboard\backend\README.md"
if not exist "dashboard\backend\__init__.py" type nul > "dashboard\backend\__init__.py"
if not exist "dashboard\backend\app\__init__.py" type nul > "dashboard\backend\app\__init__.py"
if not exist "dashboard\backend\app\main.py" type nul > "dashboard\backend\app\main.py"
if not exist "dashboard\backend\app\routers\__init__.py" type nul > "dashboard\backend\app\routers\__init__.py"
if not exist "dashboard\backend\app\routers\comparison.py" type nul > "dashboard\backend\app\routers\comparison.py"
if not exist "dashboard\backend\app\routers\graph.py" type nul > "dashboard\backend\app\routers\graph.py"
if not exist "dashboard\backend\app\routers\inference.py" type nul > "dashboard\backend\app\routers\inference.py"
if not exist "dashboard\backend\app\routers\labels.py" type nul > "dashboard\backend\app\routers\labels.py"
if not exist "dashboard\backend\app\routers\scenarios.py" type nul > "dashboard\backend\app\routers\scenarios.py"
if not exist "dashboard\backend\app\routers\timeseries.py" type nul > "dashboard\backend\app\routers\timeseries.py"
if not exist "dashboard\backend\app\schemas.py" type nul > "dashboard\backend\app\schemas.py"
if not exist "dashboard\frontend\README.md" type nul > "dashboard\frontend\README.md"
if not exist "dashboard\frontend\package.json" type nul > "dashboard\frontend\package.json"
if not exist "dashboard\frontend\src\README.md" type nul > "dashboard\frontend\src\README.md"
if not exist "data\README.md" type nul > "data\README.md"
if not exist "data\cfast_raw\.gitkeep" type nul > "data\cfast_raw\.gitkeep"
if not exist "data\datasets\.gitkeep" type nul > "data\datasets\.gitkeep"
if not exist "data\fds_raw\.gitkeep" type nul > "data\fds_raw\.gitkeep"
if not exist "data\processed\.gitkeep" type nul > "data\processed\.gitkeep"
if not exist "data\raw_ifc\.gitkeep" type nul > "data\raw_ifc\.gitkeep"
if not exist "docker-compose.yml" type nul > "docker-compose.yml"
if not exist "docs\checkin_notes\README.md" type nul > "docs\checkin_notes\README.md"
if not exist "docs\data_contracts.md" type nul > "docs\data_contracts.md"
if not exist "docs\learning_notes\README.md" type nul > "docs\learning_notes\README.md"
if not exist "docs\migration_plan.md" type nul > "docs\migration_plan.md"
if not exist "docs\modules\01_bim_graph.md" type nul > "docs\modules\01_bim_graph.md"
if not exist "docs\modules\02_cfast_scenarios.md" type nul > "docs\modules\02_cfast_scenarios.md"
if not exist "docs\modules\03_iot_dataset.md" type nul > "docs\modules\03_iot_dataset.md"
if not exist "docs\modules\04_ai_models.md" type nul > "docs\modules\04_ai_models.md"
if not exist "docs\modules\05_fds_dashboard.md" type nul > "docs\modules\05_fds_dashboard.md"
if not exist "docs\repo_review.md" type nul > "docs\repo_review.md"
if not exist "notebooks\README.md" type nul > "notebooks\README.md"
if not exist "outputs\README.md" type nul > "outputs\README.md"
if not exist "pyproject.toml" type nul > "pyproject.toml"
if not exist "report\README.md" type nul > "report\README.md"
if not exist "requirements.txt" type nul > "requirements.txt"
if not exist "scripts\README.md" type nul > "scripts\README.md"
if not exist "scripts\check.cmd" type nul > "scripts\check.cmd"
if not exist "scripts\test.cmd" type nul > "scripts\test.cmd"
if not exist "src\fire_smoke_dt\__init__.py" type nul > "src\fire_smoke_dt\__init__.py"
if not exist "src\fire_smoke_dt\bim_graph\README.md" type nul > "src\fire_smoke_dt\bim_graph\README.md"
if not exist "src\fire_smoke_dt\bim_graph\__init__.py" type nul > "src\fire_smoke_dt\bim_graph\__init__.py"
if not exist "src\fire_smoke_dt\bim_graph\fallback_manual_graph.py" type nul > "src\fire_smoke_dt\bim_graph\fallback_manual_graph.py"
if not exist "src\fire_smoke_dt\bim_graph\graph_builder.py" type nul > "src\fire_smoke_dt\bim_graph\graph_builder.py"
if not exist "src\fire_smoke_dt\bim_graph\ifc_export_notes.md" type nul > "src\fire_smoke_dt\bim_graph\ifc_export_notes.md"
if not exist "src\fire_smoke_dt\bim_graph\ifc_parser.py" type nul > "src\fire_smoke_dt\bim_graph\ifc_parser.py"
if not exist "src\fire_smoke_dt\bim_graph\topology_check.py" type nul > "src\fire_smoke_dt\bim_graph\topology_check.py"
if not exist "src\fire_smoke_dt\cfast_sim\README.md" type nul > "src\fire_smoke_dt\cfast_sim\README.md"
if not exist "src\fire_smoke_dt\cfast_sim\__init__.py" type nul > "src\fire_smoke_dt\cfast_sim\__init__.py"
if not exist "src\fire_smoke_dt\cfast_sim\batch_runner.py" type nul > "src\fire_smoke_dt\cfast_sim\batch_runner.py"
if not exist "src\fire_smoke_dt\cfast_sim\input_writer.py" type nul > "src\fire_smoke_dt\cfast_sim\input_writer.py"
if not exist "src\fire_smoke_dt\cfast_sim\postprocess.py" type nul > "src\fire_smoke_dt\cfast_sim\postprocess.py"
if not exist "src\fire_smoke_dt\comparison\README.md" type nul > "src\fire_smoke_dt\comparison\README.md"
if not exist "src\fire_smoke_dt\comparison\__init__.py" type nul > "src\fire_smoke_dt\comparison\__init__.py"
if not exist "src\fire_smoke_dt\comparison\alignment.py" type nul > "src\fire_smoke_dt\comparison\alignment.py"
if not exist "src\fire_smoke_dt\comparison\metrics.py" type nul > "src\fire_smoke_dt\comparison\metrics.py"
if not exist "src\fire_smoke_dt\dataset\README.md" type nul > "src\fire_smoke_dt\dataset\README.md"
if not exist "src\fire_smoke_dt\dataset\__init__.py" type nul > "src\fire_smoke_dt\dataset\__init__.py"
if not exist "src\fire_smoke_dt\dataset\build_dataset.py" type nul > "src\fire_smoke_dt\dataset\build_dataset.py"
if not exist "src\fire_smoke_dt\dataset\split_builder.py" type nul > "src\fire_smoke_dt\dataset\split_builder.py"
if not exist "src\fire_smoke_dt\dataset\windowing.py" type nul > "src\fire_smoke_dt\dataset\windowing.py"
if not exist "src\fire_smoke_dt\fds_sim\README.md" type nul > "src\fire_smoke_dt\fds_sim\README.md"
if not exist "src\fire_smoke_dt\fds_sim\__init__.py" type nul > "src\fire_smoke_dt\fds_sim\__init__.py"
if not exist "src\fire_smoke_dt\fds_sim\cases.py" type nul > "src\fire_smoke_dt\fds_sim\cases.py"
if not exist "src\fire_smoke_dt\fds_sim\input_writer.py" type nul > "src\fire_smoke_dt\fds_sim\input_writer.py"
if not exist "src\fire_smoke_dt\fds_sim\postprocess.py" type nul > "src\fire_smoke_dt\fds_sim\postprocess.py"
if not exist "src\fire_smoke_dt\iot_sim\README.md" type nul > "src\fire_smoke_dt\iot_sim\README.md"
if not exist "src\fire_smoke_dt\iot_sim\__init__.py" type nul > "src\fire_smoke_dt\iot_sim\__init__.py"
if not exist "src\fire_smoke_dt\iot_sim\noise_models.py" type nul > "src\fire_smoke_dt\iot_sim\noise_models.py"
if not exist "src\fire_smoke_dt\iot_sim\presets.py" type nul > "src\fire_smoke_dt\iot_sim\presets.py"
if not exist "src\fire_smoke_dt\iot_sim\simulator.py" type nul > "src\fire_smoke_dt\iot_sim\simulator.py"
if not exist "src\fire_smoke_dt\models\README.md" type nul > "src\fire_smoke_dt\models\README.md"
if not exist "src\fire_smoke_dt\models\__init__.py" type nul > "src\fire_smoke_dt\models\__init__.py"
if not exist "src\fire_smoke_dt\models\baselines\__init__.py" type nul > "src\fire_smoke_dt\models\baselines\__init__.py"
if not exist "src\fire_smoke_dt\models\baselines\graph_gnn.py" type nul > "src\fire_smoke_dt\models\baselines\graph_gnn.py"
if not exist "src\fire_smoke_dt\models\baselines\non_graph_lstm.py" type nul > "src\fire_smoke_dt\models\baselines\non_graph_lstm.py"
if not exist "src\fire_smoke_dt\models\baselines\rule_based.py" type nul > "src\fire_smoke_dt\models\baselines\rule_based.py"
if not exist "src\fire_smoke_dt\models\bat_gnn.py" type nul > "src\fire_smoke_dt\models\bat_gnn.py"
if not exist "src\fire_smoke_dt\models\temporal_gnn.py" type nul > "src\fire_smoke_dt\models\temporal_gnn.py"
if not exist "src\fire_smoke_dt\scenario\README.md" type nul > "src\fire_smoke_dt\scenario\README.md"
if not exist "src\fire_smoke_dt\scenario\__init__.py" type nul > "src\fire_smoke_dt\scenario\__init__.py"
if not exist "src\fire_smoke_dt\scenario\catalog.py" type nul > "src\fire_smoke_dt\scenario\catalog.py"
if not exist "src\fire_smoke_dt\scenario\sampler.py" type nul > "src\fire_smoke_dt\scenario\sampler.py"
if not exist "src\fire_smoke_dt\shared\README.md" type nul > "src\fire_smoke_dt\shared\README.md"
if not exist "src\fire_smoke_dt\shared\__init__.py" type nul > "src\fire_smoke_dt\shared\__init__.py"
if not exist "src\fire_smoke_dt\shared\io_utils.py" type nul > "src\fire_smoke_dt\shared\io_utils.py"
if not exist "src\fire_smoke_dt\shared\labels.py" type nul > "src\fire_smoke_dt\shared\labels.py"
if not exist "src\fire_smoke_dt\shared\logging_utils.py" type nul > "src\fire_smoke_dt\shared\logging_utils.py"
if not exist "src\fire_smoke_dt\shared\paths.py" type nul > "src\fire_smoke_dt\shared\paths.py"
if not exist "src\fire_smoke_dt\shared\schema.py" type nul > "src\fire_smoke_dt\shared\schema.py"
if not exist "src\fire_smoke_dt\shared\validation.py" type nul > "src\fire_smoke_dt\shared\validation.py"
if not exist "src\fire_smoke_dt\training\README.md" type nul > "src\fire_smoke_dt\training\README.md"
if not exist "src\fire_smoke_dt\training\__init__.py" type nul > "src\fire_smoke_dt\training\__init__.py"
if not exist "src\fire_smoke_dt\training\evaluate.py" type nul > "src\fire_smoke_dt\training\evaluate.py"
if not exist "src\fire_smoke_dt\training\losses.py" type nul > "src\fire_smoke_dt\training\losses.py"
if not exist "src\fire_smoke_dt\training\metrics.py" type nul > "src\fire_smoke_dt\training\metrics.py"
if not exist "src\fire_smoke_dt\training\train.py" type nul > "src\fire_smoke_dt\training\train.py"
if not exist "tests\fixtures\README.md" type nul > "tests\fixtures\README.md"
if not exist "tests\integration\test_data_contracts.py" type nul > "tests\integration\test_data_contracts.py"
if not exist "tests\unit\bim_graph\test_graph_builder.py" type nul > "tests\unit\bim_graph\test_graph_builder.py"
if not exist "tests\unit\dataset\test_split_builder.py" type nul > "tests\unit\dataset\test_split_builder.py"
if not exist "tests\unit\iot_sim\test_noise_models.py" type nul > "tests\unit\iot_sim\test_noise_models.py"
if not exist "tests\unit\shared\test_labels.py" type nul > "tests\unit\shared\test_labels.py"
popd
echo Tree created at %ROOT%
echo Run bootstrap_repo.cmd to write full templates.
endlocal
